### PR TITLE
Update Google verification

### PR DESCRIPTION
**Pull request by sarahzdev**
**Summary**
Update `verifyIDToken` to call [tokeninfo](https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint) endpoint to verify Google ID token

### CODE REVIEW

**Comment by hwrdtm** [comment]
Looking at the [docs](https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint)

> It is not suitable for use in production code as requests may be throttled or otherwise subject to intermittent errors.

I'm not sure how I feel about this being used in Prod.

I was looking through the Google SDK code for `verifyIdToken` and it seems it only verifies against the audience [**if it's provided**](https://github.com/googleapis/google-auth-library-nodejs/blob/bdc6339014ae13945bbf82576f7ff71534851ab1/src/auth/oauth2client.ts#L1395) - can we instead just omit that field? 

cc @glitch003

**Comment by glitch003** [comment]
yeah that works too @hwrdtm .  is that easy to do with the oauth SDK we're using @sarahzdev ?

**Comment by glitch003** [comment]
oh another option is to just not use this flow at all.  we support the google oauth JWT flow instead of the id token flow on the nodes, which requires no HTTP requests and honestly we should be pushing that flow as the default wherever possible

**Comment by hwrdtm** [comment]
> oh another option is to just not use this flow at all. we support the google oauth JWT flow instead of the id token flow on the nodes, which requires no HTTP requests and honestly we should be pushing that flow as the default wherever possible

the current flow _is_ the flow that does JWT verification (https://github.com/googleapis/google-auth-library-nodejs/blob/bdc6339014ae13945bbf82576f7ff71534851ab1/src/auth/oauth2client.ts#L1270), and AFAICS the only network call that would need to be done is to get the Google PubKeys (https://github.com/googleapis/google-auth-library-nodejs/blob/bdc6339014ae13945bbf82576f7ff71534851ab1/src/auth/oauth2client.ts#L1146) - seems this call is cached too (https://github.com/googleapis/google-auth-library-nodejs/blob/bdc6339014ae13945bbf82576f7ff71534851ab1/src/auth/oauth2client.ts#L1151-L1157)

**Comment by hwrdtm** [comment]
> Is it possible to make the google library not check against that client id? like what happens if we just don't pass a client id?

The flow will work just fine, it just will do the rest of the verification without checking audience information. As in, this block will simply not run https://github.com/googleapis/google-auth-library-nodejs/blob/bdc6339014ae13945bbf82576f7ff71534851ab1/src/auth/oauth2client.ts#L1394-L1412. **We just need a 1-liner change in that file.**

> You could grab those google certificates on startup of the server and store them locally on the disk though

The SDK already does that caching for you in-memory, but we can cache on disk if we want. Not sure how that works with Heroku though.

**Comment by glitch003** [comment]
ok cool, so the solution is to fork the google-auth-library-nodejs project and remove that audience check?

**Comment by hwrdtm** [comment]
> ok cool, so the solution is to fork the google-auth-library-nodejs project and remove that audience check?

No haha, i meant 1-liner change in our file that uses the Google SDK. I meant instead of this
```javascript
	const ticket = await client.verifyIdToken({
		idToken,
		audience: CLIENT_ID,
	});
```
We do this:
```javascript
	const ticket = await client.verifyIdToken({
		idToken,
	});
```

See the `audience` parameter is marked as optional: https://github.com/googleapis/google-auth-library-nodejs/blob/bdc6339014ae13945bbf82576f7ff71534851ab1/src/auth/oauth2client.ts#L395

**Review by hwrdtm — APPROVED** [review]

**Comment by glitch003** [comment]
Oh cool, awesome.  Thanks for clarifying @hwrdtm and thanks for putting in the fix @sarahzdev

**Pull request merged**
