### PR TITLE
Feature/lit 1004 add sequencing logic from domain wallets to chain relayer

### PR DESCRIPTION
**Pull request by joshLong145**
# WHAT
Adds a queuing layer to transaction execution or help with `nonce` ordering with high request spikes

# Testing
Created a small test script executing 200 mint transactions with `1 second` wait calls to prevent rate limiting.
Script can be found [here](https://gist.github.com/joshLong145/863bbc6b1c0d729f51603a6edf5132fe)
```
Successful requests: 200

Failed requests: 0

Average response time: 1248.66ms
```

### CODE REVIEW

**Comment by joshLong145** [comment]
@hwrdtm `nonce` sequencing has been refactored to use a local variable cache. the test results in the summary are with the changes implemented.

**Comment by hwrdtm** [comment]
@joshLong145 can you share the load test script please? In a gist or can commit it here too.

**Comment by hwrdtm** [comment]
I would love for us to look into using something like [k6](https://k6.io/docs/) for writing load tests and then incorporating it into CI too.

**Comment by joshLong145** [comment]
> @joshLong145 can you share the load test script please? In a gist or can commit it here too.

Script has been added to the PR description.

**Comment by hwrdtm** [comment]
@joshLong145 I don't think the script accurately tests what we want:
- We are spacing out each API request by 1s, instead of simulating a burst of 200 concurrent requests at a time.
- What rate limit are we trying to avoid here anyway, the downstream RPC provider's? (Infura, Alchemy)
- The client has to be conscious about avoiding rate limits, when I think a better UX would be clients just fire requests whenever they want most of the time, until they get some backpressure feedback (not saying we should build this out now) because our queue's internal buffer becomes unwieldy and we tell them to come back at a later time. In other words, if the 1s rate limit is for RPC providers, I think this concept should be kept internal to the relay server itself. We should support clients who simply just want to send 200+ concurrent requests to our server.
  - I think this is separate from a backpressure scheme where we inform clients to try again at some later time (very common in public APIs, eg. Discord's or Linear's), which I'm all for, but the backpressure scheme isn't so much related to throughput as it is related to the internal buffer of our queuing system being full, and hence we have to ask clients to come back later.

What do you think? Happy to get this merged in and do proper testing in separate PR too.

**Comment by joshLong145** [comment]
> @joshLong145 I don't think the script accurately tests what we want:
> 
> * We are spacing out each API request by 1s, instead of simulating a burst of 200 concurrent requests at a time.
> * What rate limit are we trying to avoid here anyway, the downstream RPC provider's? (Infura, Alchemy)
> * The client has to be conscious about avoiding rate limits, when I think a better UX would be clients just fire requests whenever they want most of the time, until they get some backpressure feedback (not saying we should build this out now) because our queue's internal buffer becomes unwieldy and we tell them to come back at a later time. In other words, if the 1s rate limit is for RPC providers, I think this concept should be kept internal to the relay server itself. We should support clients who simply just want to send 200+ concurrent requests to our server.
>   
>   * I think this is separate from a backpressure scheme where we inform clients to try again at some later time (very common in public APIs, eg. Discord's or Linear's), which I'm all for, but the backpressure scheme isn't so much related to throughput as it is related to the internal buffer of our queuing system being full, and hence we have to ask clients to come back later.
> 
> What do you think? Happy to get this merged in and do proper testing in separate PR too.


I see what you mean and changed the script to batch and fire a specified quantity of requests and wait for them all to finish. This required removing the rate limiting middleware that is used. The results are still the same with `0` failed requests but the average response time measuring is being thrown off. but it does work well to record failed / successful requests and all still transact when batch fired.  
I see what you mean by the back pressure problem. but with the current middleware implementation it wont even hit the given request handler if the rate limit is reached, so i dont think its a concern at this time in the way you are outlining. however, if you mean that current rate limiting implementation should be changed to be enforced in the queuing agent then we can do that once this is merged in and we spec it out a bit further.

**Review by hwrdtm — APPROVED** [review]

**Pull request merged**
